export const Commands = {
    HELP: 'help',
    ACCOUNT: 'account',
    ALERT: 'alert',
    CREATE: 'create',
    NOTE: 'note',
    CONFIGURE: 'configure',
    SETTINGS: 'settings',
    TEAM: 'team',
    LIST: 'list',
    SUBSCRIPTION: 'subscription',
    ADD: 'add',
    DELETE: 'delete',
    CLOSE: 'close',
    ACK: 'ack',
    UNACK: 'unack',
    SNOOZE: 'snooze',
    ASSIGN: 'assign',
    OWN: 'own',
    PRIORITY: 'priority',
    LOGIN: 'login',
    LOGOUT: 'logout',
};
